package learning

// Code generated by http://github.com/gojuno/minimock (dev). DO NOT EDIT.

//go:generate minimock -i hw4/internal/learning.TutorServiceInterface -o ./internal\learning\group_service_mock_test.go -topN GroupServiceMock

import (
	"sync"
	mm_atomic "sync/atomic"
	mm_time "time"

	"github.com/gojuno/minimock/v3"
)

// GroupServiceMock implements TutorServiceInterface
type GroupServiceMock struct {
	t minimock.Tester

	funcSubjects          func() (sa1 []string)
	inspectFuncSubjects   func()
	afterSubjectsCounter  uint64
	beforeSubjectsCounter uint64
	SubjectsMock          mGroupServiceMockSubjects

	funcTutorsID          func(subject string) (ia1 []int64)
	inspectFuncTutorsID   func(subject string)
	afterTutorsIDCounter  uint64
	beforeTutorsIDCounter uint64
	TutorsIDMock          mGroupServiceMockTutorsID
}

// NewGroupServiceMock returns a mock for TutorServiceInterface
func NewGroupServiceMock(t minimock.Tester) *GroupServiceMock {
	m := &GroupServiceMock{t: t}
	if controller, ok := t.(minimock.MockController); ok {
		controller.RegisterMocker(m)
	}

	m.SubjectsMock = mGroupServiceMockSubjects{mock: m}

	m.TutorsIDMock = mGroupServiceMockTutorsID{mock: m}
	m.TutorsIDMock.callArgs = []*GroupServiceMockTutorsIDParams{}

	return m
}

type mGroupServiceMockSubjects struct {
	mock               *GroupServiceMock
	defaultExpectation *GroupServiceMockSubjectsExpectation
	expectations       []*GroupServiceMockSubjectsExpectation
}

// GroupServiceMockSubjectsExpectation specifies expectation struct of the TutorServiceInterface.Subjects
type GroupServiceMockSubjectsExpectation struct {
	mock *GroupServiceMock

	results *GroupServiceMockSubjectsResults
	Counter uint64
}

// GroupServiceMockSubjectsResults contains results of the TutorServiceInterface.Subjects
type GroupServiceMockSubjectsResults struct {
	sa1 []string
}

// Expect sets up expected params for TutorServiceInterface.Subjects
func (mmSubjects *mGroupServiceMockSubjects) Expect() *mGroupServiceMockSubjects {
	if mmSubjects.mock.funcSubjects != nil {
		mmSubjects.mock.t.Fatalf("GroupServiceMock.Subjects mock is already set by Set")
	}

	if mmSubjects.defaultExpectation == nil {
		mmSubjects.defaultExpectation = &GroupServiceMockSubjectsExpectation{}
	}

	return mmSubjects
}

// Inspect accepts an inspector function that has same arguments as the TutorServiceInterface.Subjects
func (mmSubjects *mGroupServiceMockSubjects) Inspect(f func()) *mGroupServiceMockSubjects {
	if mmSubjects.mock.inspectFuncSubjects != nil {
		mmSubjects.mock.t.Fatalf("Inspect function is already set for GroupServiceMock.Subjects")
	}

	mmSubjects.mock.inspectFuncSubjects = f

	return mmSubjects
}

// Return sets up results that will be returned by TutorServiceInterface.Subjects
func (mmSubjects *mGroupServiceMockSubjects) Return(sa1 []string) *GroupServiceMock {
	if mmSubjects.mock.funcSubjects != nil {
		mmSubjects.mock.t.Fatalf("GroupServiceMock.Subjects mock is already set by Set")
	}

	if mmSubjects.defaultExpectation == nil {
		mmSubjects.defaultExpectation = &GroupServiceMockSubjectsExpectation{mock: mmSubjects.mock}
	}
	mmSubjects.defaultExpectation.results = &GroupServiceMockSubjectsResults{sa1}
	return mmSubjects.mock
}

// Set uses given function f to mock the TutorServiceInterface.Subjects method
func (mmSubjects *mGroupServiceMockSubjects) Set(f func() (sa1 []string)) *GroupServiceMock {
	if mmSubjects.defaultExpectation != nil {
		mmSubjects.mock.t.Fatalf("Default expectation is already set for the TutorServiceInterface.Subjects method")
	}

	if len(mmSubjects.expectations) > 0 {
		mmSubjects.mock.t.Fatalf("Some expectations are already set for the TutorServiceInterface.Subjects method")
	}

	mmSubjects.mock.funcSubjects = f
	return mmSubjects.mock
}

// Subjects implements TutorServiceInterface
func (mmSubjects *GroupServiceMock) Subjects() (sa1 []string) {
	mm_atomic.AddUint64(&mmSubjects.beforeSubjectsCounter, 1)
	defer mm_atomic.AddUint64(&mmSubjects.afterSubjectsCounter, 1)

	if mmSubjects.inspectFuncSubjects != nil {
		mmSubjects.inspectFuncSubjects()
	}

	if mmSubjects.SubjectsMock.defaultExpectation != nil {
		mm_atomic.AddUint64(&mmSubjects.SubjectsMock.defaultExpectation.Counter, 1)

		mm_results := mmSubjects.SubjectsMock.defaultExpectation.results
		if mm_results == nil {
			mmSubjects.t.Fatal("No results are set for the GroupServiceMock.Subjects")
		}
		return (*mm_results).sa1
	}
	if mmSubjects.funcSubjects != nil {
		return mmSubjects.funcSubjects()
	}
	mmSubjects.t.Fatalf("Unexpected call to GroupServiceMock.Subjects.")
	return
}

// SubjectsAfterCounter returns a count of finished GroupServiceMock.Subjects invocations
func (mmSubjects *GroupServiceMock) SubjectsAfterCounter() uint64 {
	return mm_atomic.LoadUint64(&mmSubjects.afterSubjectsCounter)
}

// SubjectsBeforeCounter returns a count of GroupServiceMock.Subjects invocations
func (mmSubjects *GroupServiceMock) SubjectsBeforeCounter() uint64 {
	return mm_atomic.LoadUint64(&mmSubjects.beforeSubjectsCounter)
}

// MinimockSubjectsDone returns true if the count of the Subjects invocations corresponds
// the number of defined expectations
func (m *GroupServiceMock) MinimockSubjectsDone() bool {
	for _, e := range m.SubjectsMock.expectations {
		if mm_atomic.LoadUint64(&e.Counter) < 1 {
			return false
		}
	}

	// if default expectation was set then invocations count should be greater than zero
	if m.SubjectsMock.defaultExpectation != nil && mm_atomic.LoadUint64(&m.afterSubjectsCounter) < 1 {
		return false
	}
	// if func was set then invocations count should be greater than zero
	if m.funcSubjects != nil && mm_atomic.LoadUint64(&m.afterSubjectsCounter) < 1 {
		return false
	}
	return true
}

// MinimockSubjectsInspect logs each unmet expectation
func (m *GroupServiceMock) MinimockSubjectsInspect() {
	for _, e := range m.SubjectsMock.expectations {
		if mm_atomic.LoadUint64(&e.Counter) < 1 {
			m.t.Error("Expected call to GroupServiceMock.Subjects")
		}
	}

	// if default expectation was set then invocations count should be greater than zero
	if m.SubjectsMock.defaultExpectation != nil && mm_atomic.LoadUint64(&m.afterSubjectsCounter) < 1 {
		m.t.Error("Expected call to GroupServiceMock.Subjects")
	}
	// if func was set then invocations count should be greater than zero
	if m.funcSubjects != nil && mm_atomic.LoadUint64(&m.afterSubjectsCounter) < 1 {
		m.t.Error("Expected call to GroupServiceMock.Subjects")
	}
}

type mGroupServiceMockTutorsID struct {
	mock               *GroupServiceMock
	defaultExpectation *GroupServiceMockTutorsIDExpectation
	expectations       []*GroupServiceMockTutorsIDExpectation

	callArgs []*GroupServiceMockTutorsIDParams
	mutex    sync.RWMutex
}

// GroupServiceMockTutorsIDExpectation specifies expectation struct of the TutorServiceInterface.TutorsID
type GroupServiceMockTutorsIDExpectation struct {
	mock    *GroupServiceMock
	params  *GroupServiceMockTutorsIDParams
	results *GroupServiceMockTutorsIDResults
	Counter uint64
}

// GroupServiceMockTutorsIDParams contains parameters of the TutorServiceInterface.TutorsID
type GroupServiceMockTutorsIDParams struct {
	subject string
}

// GroupServiceMockTutorsIDResults contains results of the TutorServiceInterface.TutorsID
type GroupServiceMockTutorsIDResults struct {
	ia1 []int64
}

// Expect sets up expected params for TutorServiceInterface.TutorsID
func (mmTutorsID *mGroupServiceMockTutorsID) Expect(subject string) *mGroupServiceMockTutorsID {
	if mmTutorsID.mock.funcTutorsID != nil {
		mmTutorsID.mock.t.Fatalf("GroupServiceMock.TutorsID mock is already set by Set")
	}

	if mmTutorsID.defaultExpectation == nil {
		mmTutorsID.defaultExpectation = &GroupServiceMockTutorsIDExpectation{}
	}

	mmTutorsID.defaultExpectation.params = &GroupServiceMockTutorsIDParams{subject}
	for _, e := range mmTutorsID.expectations {
		if minimock.Equal(e.params, mmTutorsID.defaultExpectation.params) {
			mmTutorsID.mock.t.Fatalf("Expectation set by When has same params: %#v", *mmTutorsID.defaultExpectation.params)
		}
	}

	return mmTutorsID
}

// Inspect accepts an inspector function that has same arguments as the TutorServiceInterface.TutorsID
func (mmTutorsID *mGroupServiceMockTutorsID) Inspect(f func(subject string)) *mGroupServiceMockTutorsID {
	if mmTutorsID.mock.inspectFuncTutorsID != nil {
		mmTutorsID.mock.t.Fatalf("Inspect function is already set for GroupServiceMock.TutorsID")
	}

	mmTutorsID.mock.inspectFuncTutorsID = f

	return mmTutorsID
}

// Return sets up results that will be returned by TutorServiceInterface.TutorsID
func (mmTutorsID *mGroupServiceMockTutorsID) Return(ia1 []int64) *GroupServiceMock {
	if mmTutorsID.mock.funcTutorsID != nil {
		mmTutorsID.mock.t.Fatalf("GroupServiceMock.TutorsID mock is already set by Set")
	}

	if mmTutorsID.defaultExpectation == nil {
		mmTutorsID.defaultExpectation = &GroupServiceMockTutorsIDExpectation{mock: mmTutorsID.mock}
	}
	mmTutorsID.defaultExpectation.results = &GroupServiceMockTutorsIDResults{ia1}
	return mmTutorsID.mock
}

// Set uses given function f to mock the TutorServiceInterface.TutorsID method
func (mmTutorsID *mGroupServiceMockTutorsID) Set(f func(subject string) (ia1 []int64)) *GroupServiceMock {
	if mmTutorsID.defaultExpectation != nil {
		mmTutorsID.mock.t.Fatalf("Default expectation is already set for the TutorServiceInterface.TutorsID method")
	}

	if len(mmTutorsID.expectations) > 0 {
		mmTutorsID.mock.t.Fatalf("Some expectations are already set for the TutorServiceInterface.TutorsID method")
	}

	mmTutorsID.mock.funcTutorsID = f
	return mmTutorsID.mock
}

// When sets expectation for the TutorServiceInterface.TutorsID which will trigger the result defined by the following
// Then helper
func (mmTutorsID *mGroupServiceMockTutorsID) When(subject string) *GroupServiceMockTutorsIDExpectation {
	if mmTutorsID.mock.funcTutorsID != nil {
		mmTutorsID.mock.t.Fatalf("GroupServiceMock.TutorsID mock is already set by Set")
	}

	expectation := &GroupServiceMockTutorsIDExpectation{
		mock:   mmTutorsID.mock,
		params: &GroupServiceMockTutorsIDParams{subject},
	}
	mmTutorsID.expectations = append(mmTutorsID.expectations, expectation)
	return expectation
}

// Then sets up TutorServiceInterface.TutorsID return parameters for the expectation previously defined by the When method
func (e *GroupServiceMockTutorsIDExpectation) Then(ia1 []int64) *GroupServiceMock {
	e.results = &GroupServiceMockTutorsIDResults{ia1}
	return e.mock
}

// TutorsID implements TutorServiceInterface
func (mmTutorsID *GroupServiceMock) TutorsID(subject string) (ia1 []int64) {
	mm_atomic.AddUint64(&mmTutorsID.beforeTutorsIDCounter, 1)
	defer mm_atomic.AddUint64(&mmTutorsID.afterTutorsIDCounter, 1)

	if mmTutorsID.inspectFuncTutorsID != nil {
		mmTutorsID.inspectFuncTutorsID(subject)
	}

	mm_params := &GroupServiceMockTutorsIDParams{subject}

	// Record call args
	mmTutorsID.TutorsIDMock.mutex.Lock()
	mmTutorsID.TutorsIDMock.callArgs = append(mmTutorsID.TutorsIDMock.callArgs, mm_params)
	mmTutorsID.TutorsIDMock.mutex.Unlock()

	for _, e := range mmTutorsID.TutorsIDMock.expectations {
		if minimock.Equal(e.params, mm_params) {
			mm_atomic.AddUint64(&e.Counter, 1)
			return e.results.ia1
		}
	}

	if mmTutorsID.TutorsIDMock.defaultExpectation != nil {
		mm_atomic.AddUint64(&mmTutorsID.TutorsIDMock.defaultExpectation.Counter, 1)
		mm_want := mmTutorsID.TutorsIDMock.defaultExpectation.params
		mm_got := GroupServiceMockTutorsIDParams{subject}
		if mm_want != nil && !minimock.Equal(*mm_want, mm_got) {
			mmTutorsID.t.Errorf("GroupServiceMock.TutorsID got unexpected parameters, want: %#v, got: %#v%s\n", *mm_want, mm_got, minimock.Diff(*mm_want, mm_got))
		}

		mm_results := mmTutorsID.TutorsIDMock.defaultExpectation.results
		if mm_results == nil {
			mmTutorsID.t.Fatal("No results are set for the GroupServiceMock.TutorsID")
		}
		return (*mm_results).ia1
	}
	if mmTutorsID.funcTutorsID != nil {
		return mmTutorsID.funcTutorsID(subject)
	}
	mmTutorsID.t.Fatalf("Unexpected call to GroupServiceMock.TutorsID. %v", subject)
	return
}

// TutorsIDAfterCounter returns a count of finished GroupServiceMock.TutorsID invocations
func (mmTutorsID *GroupServiceMock) TutorsIDAfterCounter() uint64 {
	return mm_atomic.LoadUint64(&mmTutorsID.afterTutorsIDCounter)
}

// TutorsIDBeforeCounter returns a count of GroupServiceMock.TutorsID invocations
func (mmTutorsID *GroupServiceMock) TutorsIDBeforeCounter() uint64 {
	return mm_atomic.LoadUint64(&mmTutorsID.beforeTutorsIDCounter)
}

// Calls returns a list of arguments used in each call to GroupServiceMock.TutorsID.
// The list is in the same order as the calls were made (i.e. recent calls have a higher index)
func (mmTutorsID *mGroupServiceMockTutorsID) Calls() []*GroupServiceMockTutorsIDParams {
	mmTutorsID.mutex.RLock()

	argCopy := make([]*GroupServiceMockTutorsIDParams, len(mmTutorsID.callArgs))
	copy(argCopy, mmTutorsID.callArgs)

	mmTutorsID.mutex.RUnlock()

	return argCopy
}

// MinimockTutorsIDDone returns true if the count of the TutorsID invocations corresponds
// the number of defined expectations
func (m *GroupServiceMock) MinimockTutorsIDDone() bool {
	for _, e := range m.TutorsIDMock.expectations {
		if mm_atomic.LoadUint64(&e.Counter) < 1 {
			return false
		}
	}

	// if default expectation was set then invocations count should be greater than zero
	if m.TutorsIDMock.defaultExpectation != nil && mm_atomic.LoadUint64(&m.afterTutorsIDCounter) < 1 {
		return false
	}
	// if func was set then invocations count should be greater than zero
	if m.funcTutorsID != nil && mm_atomic.LoadUint64(&m.afterTutorsIDCounter) < 1 {
		return false
	}
	return true
}

// MinimockTutorsIDInspect logs each unmet expectation
func (m *GroupServiceMock) MinimockTutorsIDInspect() {
	for _, e := range m.TutorsIDMock.expectations {
		if mm_atomic.LoadUint64(&e.Counter) < 1 {
			m.t.Errorf("Expected call to GroupServiceMock.TutorsID with params: %#v", *e.params)
		}
	}

	// if default expectation was set then invocations count should be greater than zero
	if m.TutorsIDMock.defaultExpectation != nil && mm_atomic.LoadUint64(&m.afterTutorsIDCounter) < 1 {
		if m.TutorsIDMock.defaultExpectation.params == nil {
			m.t.Error("Expected call to GroupServiceMock.TutorsID")
		} else {
			m.t.Errorf("Expected call to GroupServiceMock.TutorsID with params: %#v", *m.TutorsIDMock.defaultExpectation.params)
		}
	}
	// if func was set then invocations count should be greater than zero
	if m.funcTutorsID != nil && mm_atomic.LoadUint64(&m.afterTutorsIDCounter) < 1 {
		m.t.Error("Expected call to GroupServiceMock.TutorsID")
	}
}

// MinimockFinish checks that all mocked methods have been called the expected number of times
func (m *GroupServiceMock) MinimockFinish() {
	if !m.minimockDone() {
		m.MinimockSubjectsInspect()

		m.MinimockTutorsIDInspect()
		m.t.FailNow()
	}
}

// MinimockWait waits for all mocked methods to be called the expected number of times
func (m *GroupServiceMock) MinimockWait(timeout mm_time.Duration) {
	timeoutCh := mm_time.After(timeout)
	for {
		if m.minimockDone() {
			return
		}
		select {
		case <-timeoutCh:
			m.MinimockFinish()
			return
		case <-mm_time.After(10 * mm_time.Millisecond):
		}
	}
}

func (m *GroupServiceMock) minimockDone() bool {
	done := true
	return done &&
		m.MinimockSubjectsDone() &&
		m.MinimockTutorsIDDone()
}
