 package learning

// Code generated by http://github.com/gojuno/minimock (dev). DO NOT EDIT.

//go:generate minimock -i hw4/internal/learning.ServiceInterface -o ./internal\learning\service_mock_test.go -topN ServiceMock

import (
	"sync"
	mm_atomic "sync/atomic"
	mm_time "time"

	"github.com/gojuno/minimock/v3"
)

// ServiceMock implements ServiceInterface
type ServiceMock struct {
	t minimock.Tester

	funcGetTopSubjects          func(topN int) (sa1 []string, b1 bool)
	inspectFuncGetTopSubjects   func(topN int)
	afterGetTopSubjectsCounter  uint64
	beforeGetTopSubjectsCounter uint64
	GetTopSubjectsMock          mServiceMockGetTopSubjects

	funcGetTutorsIDPreferIndividual          func(studentID int64) (ia1 []int64, b1 bool)
	inspectFuncGetTutorsIDPreferIndividual   func(studentID int64)
	afterGetTutorsIDPreferIndividualCounter  uint64
	beforeGetTutorsIDPreferIndividualCounter uint64
	GetTutorsIDPreferIndividualMock          mServiceMockGetTutorsIDPreferIndividual
}

// NewServiceMock returns a mock for ServiceInterface
func NewServiceMock(t minimock.Tester) *ServiceMock {
	m := &ServiceMock{t: t}
	if controller, ok := t.(minimock.MockController); ok {
		controller.RegisterMocker(m)
	}

	m.GetTopSubjectsMock = mServiceMockGetTopSubjects{mock: m}
	m.GetTopSubjectsMock.callArgs = []*ServiceMockGetTopSubjectsParams{}

	m.GetTutorsIDPreferIndividualMock = mServiceMockGetTutorsIDPreferIndividual{mock: m}
	m.GetTutorsIDPreferIndividualMock.callArgs = []*ServiceMockGetTutorsIDPreferIndividualParams{}

	return m
}

type mServiceMockGetTopSubjects struct {
	mock               *ServiceMock
	defaultExpectation *ServiceMockGetTopSubjectsExpectation
	expectations       []*ServiceMockGetTopSubjectsExpectation

	callArgs []*ServiceMockGetTopSubjectsParams
	mutex    sync.RWMutex
}

// ServiceMockGetTopSubjectsExpectation specifies expectation struct of the ServiceInterface.GetTopSubjects
type ServiceMockGetTopSubjectsExpectation struct {
	mock    *ServiceMock
	params  *ServiceMockGetTopSubjectsParams
	results *ServiceMockGetTopSubjectsResults
	Counter uint64
}

// ServiceMockGetTopSubjectsParams contains parameters of the ServiceInterface.GetTopSubjects
type ServiceMockGetTopSubjectsParams struct {
	topN int
}

// ServiceMockGetTopSubjectsResults contains results of the ServiceInterface.GetTopSubjects
type ServiceMockGetTopSubjectsResults struct {
	sa1 []string
	b1  bool
}

// Expect sets up expected params for ServiceInterface.GetTopSubjects
func (mmGetTopSubjects *mServiceMockGetTopSubjects) Expect(topN int) *mServiceMockGetTopSubjects {
	if mmGetTopSubjects.mock.funcGetTopSubjects != nil {
		mmGetTopSubjects.mock.t.Fatalf("ServiceMock.GetTopSubjects mock is already set by Set")
	}

	if mmGetTopSubjects.defaultExpectation == nil {
		mmGetTopSubjects.defaultExpectation = &ServiceMockGetTopSubjectsExpectation{}
	}

	mmGetTopSubjects.defaultExpectation.params = &ServiceMockGetTopSubjectsParams{topN}
	for _, e := range mmGetTopSubjects.expectations {
		if minimock.Equal(e.params, mmGetTopSubjects.defaultExpectation.params) {
			mmGetTopSubjects.mock.t.Fatalf("Expectation set by When has same params: %#v", *mmGetTopSubjects.defaultExpectation.params)
		}
	}

	return mmGetTopSubjects
}

// Inspect accepts an inspector function that has same arguments as the ServiceInterface.GetTopSubjects
func (mmGetTopSubjects *mServiceMockGetTopSubjects) Inspect(f func(topN int)) *mServiceMockGetTopSubjects {
	if mmGetTopSubjects.mock.inspectFuncGetTopSubjects != nil {
		mmGetTopSubjects.mock.t.Fatalf("Inspect function is already set for ServiceMock.GetTopSubjects")
	}

	mmGetTopSubjects.mock.inspectFuncGetTopSubjects = f

	return mmGetTopSubjects
}

// Return sets up results that will be returned by ServiceInterface.GetTopSubjects
func (mmGetTopSubjects *mServiceMockGetTopSubjects) Return(sa1 []string, b1 bool) *ServiceMock {
	if mmGetTopSubjects.mock.funcGetTopSubjects != nil {
		mmGetTopSubjects.mock.t.Fatalf("ServiceMock.GetTopSubjects mock is already set by Set")
	}

	if mmGetTopSubjects.defaultExpectation == nil {
		mmGetTopSubjects.defaultExpectation = &ServiceMockGetTopSubjectsExpectation{mock: mmGetTopSubjects.mock}
	}
	mmGetTopSubjects.defaultExpectation.results = &ServiceMockGetTopSubjectsResults{sa1, b1}
	return mmGetTopSubjects.mock
}

// Set uses given function f to mock the ServiceInterface.GetTopSubjects method
func (mmGetTopSubjects *mServiceMockGetTopSubjects) Set(f func(topN int) (sa1 []string, b1 bool)) *ServiceMock {
	if mmGetTopSubjects.defaultExpectation != nil {
		mmGetTopSubjects.mock.t.Fatalf("Default expectation is already set for the ServiceInterface.GetTopSubjects method")
	}

	if len(mmGetTopSubjects.expectations) > 0 {
		mmGetTopSubjects.mock.t.Fatalf("Some expectations are already set for the ServiceInterface.GetTopSubjects method")
	}

	mmGetTopSubjects.mock.funcGetTopSubjects = f
	return mmGetTopSubjects.mock
}

// When sets expectation for the ServiceInterface.GetTopSubjects which will trigger the result defined by the following
// Then helper
func (mmGetTopSubjects *mServiceMockGetTopSubjects) When(topN int) *ServiceMockGetTopSubjectsExpectation {
	if mmGetTopSubjects.mock.funcGetTopSubjects != nil {
		mmGetTopSubjects.mock.t.Fatalf("ServiceMock.GetTopSubjects mock is already set by Set")
	}

	expectation := &ServiceMockGetTopSubjectsExpectation{
		mock:   mmGetTopSubjects.mock,
		params: &ServiceMockGetTopSubjectsParams{topN},
	}
	mmGetTopSubjects.expectations = append(mmGetTopSubjects.expectations, expectation)
	return expectation
}

// Then sets up ServiceInterface.GetTopSubjects return parameters for the expectation previously defined by the When method
func (e *ServiceMockGetTopSubjectsExpectation) Then(sa1 []string, b1 bool) *ServiceMock {
	e.results = &ServiceMockGetTopSubjectsResults{sa1, b1}
	return e.mock
}

// GetTopSubjects implements ServiceInterface
func (mmGetTopSubjects *ServiceMock) GetTopSubjects(topN int) (sa1 []string, b1 bool) {
	mm_atomic.AddUint64(&mmGetTopSubjects.beforeGetTopSubjectsCounter, 1)
	defer mm_atomic.AddUint64(&mmGetTopSubjects.afterGetTopSubjectsCounter, 1)

	if mmGetTopSubjects.inspectFuncGetTopSubjects != nil {
		mmGetTopSubjects.inspectFuncGetTopSubjects(topN)
	}

	mm_params := &ServiceMockGetTopSubjectsParams{topN}

	// Record call args
	mmGetTopSubjects.GetTopSubjectsMock.mutex.Lock()
	mmGetTopSubjects.GetTopSubjectsMock.callArgs = append(mmGetTopSubjects.GetTopSubjectsMock.callArgs, mm_params)
	mmGetTopSubjects.GetTopSubjectsMock.mutex.Unlock()

	for _, e := range mmGetTopSubjects.GetTopSubjectsMock.expectations {
		if minimock.Equal(e.params, mm_params) {
			mm_atomic.AddUint64(&e.Counter, 1)
			return e.results.sa1, e.results.b1
		}
	}

	if mmGetTopSubjects.GetTopSubjectsMock.defaultExpectation != nil {
		mm_atomic.AddUint64(&mmGetTopSubjects.GetTopSubjectsMock.defaultExpectation.Counter, 1)
		mm_want := mmGetTopSubjects.GetTopSubjectsMock.defaultExpectation.params
		mm_got := ServiceMockGetTopSubjectsParams{topN}
		if mm_want != nil && !minimock.Equal(*mm_want, mm_got) {
			mmGetTopSubjects.t.Errorf("ServiceMock.GetTopSubjects got unexpected parameters, want: %#v, got: %#v%s\n", *mm_want, mm_got, minimock.Diff(*mm_want, mm_got))
		}

		mm_results := mmGetTopSubjects.GetTopSubjectsMock.defaultExpectation.results
		if mm_results == nil {
			mmGetTopSubjects.t.Fatal("No results are set for the ServiceMock.GetTopSubjects")
		}
		return (*mm_results).sa1, (*mm_results).b1
	}
	if mmGetTopSubjects.funcGetTopSubjects != nil {
		return mmGetTopSubjects.funcGetTopSubjects(topN)
	}
	mmGetTopSubjects.t.Fatalf("Unexpected call to ServiceMock.GetTopSubjects. %v", topN)
	return
}

// GetTopSubjectsAfterCounter returns a count of finished ServiceMock.GetTopSubjects invocations
func (mmGetTopSubjects *ServiceMock) GetTopSubjectsAfterCounter() uint64 {
	return mm_atomic.LoadUint64(&mmGetTopSubjects.afterGetTopSubjectsCounter)
}

// GetTopSubjectsBeforeCounter returns a count of ServiceMock.GetTopSubjects invocations
func (mmGetTopSubjects *ServiceMock) GetTopSubjectsBeforeCounter() uint64 {
	return mm_atomic.LoadUint64(&mmGetTopSubjects.beforeGetTopSubjectsCounter)
}

// Calls returns a list of arguments used in each call to ServiceMock.GetTopSubjects.
// The list is in the same order as the calls were made (i.e. recent calls have a higher index)
func (mmGetTopSubjects *mServiceMockGetTopSubjects) Calls() []*ServiceMockGetTopSubjectsParams {
	mmGetTopSubjects.mutex.RLock()

	argCopy := make([]*ServiceMockGetTopSubjectsParams, len(mmGetTopSubjects.callArgs))
	copy(argCopy, mmGetTopSubjects.callArgs)

	mmGetTopSubjects.mutex.RUnlock()

	return argCopy
}

// MinimockGetTopSubjectsDone returns true if the count of the GetTopSubjects invocations corresponds
// the number of defined expectations
func (m *ServiceMock) MinimockGetTopSubjectsDone() bool {
	for _, e := range m.GetTopSubjectsMock.expectations {
		if mm_atomic.LoadUint64(&e.Counter) < 1 {
			return false
		}
	}

	// if default expectation was set then invocations count should be greater than zero
	if m.GetTopSubjectsMock.defaultExpectation != nil && mm_atomic.LoadUint64(&m.afterGetTopSubjectsCounter) < 1 {
		return false
	}
	// if func was set then invocations count should be greater than zero
	if m.funcGetTopSubjects != nil && mm_atomic.LoadUint64(&m.afterGetTopSubjectsCounter) < 1 {
		return false
	}
	return true
}

// MinimockGetTopSubjectsInspect logs each unmet expectation
func (m *ServiceMock) MinimockGetTopSubjectsInspect() {
	for _, e := range m.GetTopSubjectsMock.expectations {
		if mm_atomic.LoadUint64(&e.Counter) < 1 {
			m.t.Errorf("Expected call to ServiceMock.GetTopSubjects with params: %#v", *e.params)
		}
	}

	// if default expectation was set then invocations count should be greater than zero
	if m.GetTopSubjectsMock.defaultExpectation != nil && mm_atomic.LoadUint64(&m.afterGetTopSubjectsCounter) < 1 {
		if m.GetTopSubjectsMock.defaultExpectation.params == nil {
			m.t.Error("Expected call to ServiceMock.GetTopSubjects")
		} else {
			m.t.Errorf("Expected call to ServiceMock.GetTopSubjects with params: %#v", *m.GetTopSubjectsMock.defaultExpectation.params)
		}
	}
	// if func was set then invocations count should be greater than zero
	if m.funcGetTopSubjects != nil && mm_atomic.LoadUint64(&m.afterGetTopSubjectsCounter) < 1 {
		m.t.Error("Expected call to ServiceMock.GetTopSubjects")
	}
}

type mServiceMockGetTutorsIDPreferIndividual struct {
	mock               *ServiceMock
	defaultExpectation *ServiceMockGetTutorsIDPreferIndividualExpectation
	expectations       []*ServiceMockGetTutorsIDPreferIndividualExpectation

	callArgs []*ServiceMockGetTutorsIDPreferIndividualParams
	mutex    sync.RWMutex
}

// ServiceMockGetTutorsIDPreferIndividualExpectation specifies expectation struct of the ServiceInterface.GetTutorsIDPreferIndividual
type ServiceMockGetTutorsIDPreferIndividualExpectation struct {
	mock    *ServiceMock
	params  *ServiceMockGetTutorsIDPreferIndividualParams
	results *ServiceMockGetTutorsIDPreferIndividualResults
	Counter uint64
}

// ServiceMockGetTutorsIDPreferIndividualParams contains parameters of the ServiceInterface.GetTutorsIDPreferIndividual
type ServiceMockGetTutorsIDPreferIndividualParams struct {
	studentID int64
}

// ServiceMockGetTutorsIDPreferIndividualResults contains results of the ServiceInterface.GetTutorsIDPreferIndividual
type ServiceMockGetTutorsIDPreferIndividualResults struct {
	ia1 []int64
	b1  bool
}

// Expect sets up expected params for ServiceInterface.GetTutorsIDPreferIndividual
func (mmGetTutorsIDPreferIndividual *mServiceMockGetTutorsIDPreferIndividual) Expect(studentID int64) *mServiceMockGetTutorsIDPreferIndividual {
	if mmGetTutorsIDPreferIndividual.mock.funcGetTutorsIDPreferIndividual != nil {
		mmGetTutorsIDPreferIndividual.mock.t.Fatalf("ServiceMock.GetTutorsIDPreferIndividual mock is already set by Set")
	}

	if mmGetTutorsIDPreferIndividual.defaultExpectation == nil {
		mmGetTutorsIDPreferIndividual.defaultExpectation = &ServiceMockGetTutorsIDPreferIndividualExpectation{}
	}

	mmGetTutorsIDPreferIndividual.defaultExpectation.params = &ServiceMockGetTutorsIDPreferIndividualParams{studentID}
	for _, e := range mmGetTutorsIDPreferIndividual.expectations {
		if minimock.Equal(e.params, mmGetTutorsIDPreferIndividual.defaultExpectation.params) {
			mmGetTutorsIDPreferIndividual.mock.t.Fatalf("Expectation set by When has same params: %#v", *mmGetTutorsIDPreferIndividual.defaultExpectation.params)
		}
	}

	return mmGetTutorsIDPreferIndividual
}

// Inspect accepts an inspector function that has same arguments as the ServiceInterface.GetTutorsIDPreferIndividual
func (mmGetTutorsIDPreferIndividual *mServiceMockGetTutorsIDPreferIndividual) Inspect(f func(studentID int64)) *mServiceMockGetTutorsIDPreferIndividual {
	if mmGetTutorsIDPreferIndividual.mock.inspectFuncGetTutorsIDPreferIndividual != nil {
		mmGetTutorsIDPreferIndividual.mock.t.Fatalf("Inspect function is already set for ServiceMock.GetTutorsIDPreferIndividual")
	}

	mmGetTutorsIDPreferIndividual.mock.inspectFuncGetTutorsIDPreferIndividual = f

	return mmGetTutorsIDPreferIndividual
}

// Return sets up results that will be returned by ServiceInterface.GetTutorsIDPreferIndividual
func (mmGetTutorsIDPreferIndividual *mServiceMockGetTutorsIDPreferIndividual) Return(ia1 []int64, b1 bool) *ServiceMock {
	if mmGetTutorsIDPreferIndividual.mock.funcGetTutorsIDPreferIndividual != nil {
		mmGetTutorsIDPreferIndividual.mock.t.Fatalf("ServiceMock.GetTutorsIDPreferIndividual mock is already set by Set")
	}

	if mmGetTutorsIDPreferIndividual.defaultExpectation == nil {
		mmGetTutorsIDPreferIndividual.defaultExpectation = &ServiceMockGetTutorsIDPreferIndividualExpectation{mock: mmGetTutorsIDPreferIndividual.mock}
	}
	mmGetTutorsIDPreferIndividual.defaultExpectation.results = &ServiceMockGetTutorsIDPreferIndividualResults{ia1, b1}
	return mmGetTutorsIDPreferIndividual.mock
}

// Set uses given function f to mock the ServiceInterface.GetTutorsIDPreferIndividual method
func (mmGetTutorsIDPreferIndividual *mServiceMockGetTutorsIDPreferIndividual) Set(f func(studentID int64) (ia1 []int64, b1 bool)) *ServiceMock {
	if mmGetTutorsIDPreferIndividual.defaultExpectation != nil {
		mmGetTutorsIDPreferIndividual.mock.t.Fatalf("Default expectation is already set for the ServiceInterface.GetTutorsIDPreferIndividual method")
	}

	if len(mmGetTutorsIDPreferIndividual.expectations) > 0 {
		mmGetTutorsIDPreferIndividual.mock.t.Fatalf("Some expectations are already set for the ServiceInterface.GetTutorsIDPreferIndividual method")
	}

	mmGetTutorsIDPreferIndividual.mock.funcGetTutorsIDPreferIndividual = f
	return mmGetTutorsIDPreferIndividual.mock
}

// When sets expectation for the ServiceInterface.GetTutorsIDPreferIndividual which will trigger the result defined by the following
// Then helper
func (mmGetTutorsIDPreferIndividual *mServiceMockGetTutorsIDPreferIndividual) When(studentID int64) *ServiceMockGetTutorsIDPreferIndividualExpectation {
	if mmGetTutorsIDPreferIndividual.mock.funcGetTutorsIDPreferIndividual != nil {
		mmGetTutorsIDPreferIndividual.mock.t.Fatalf("ServiceMock.GetTutorsIDPreferIndividual mock is already set by Set")
	}

	expectation := &ServiceMockGetTutorsIDPreferIndividualExpectation{
		mock:   mmGetTutorsIDPreferIndividual.mock,
		params: &ServiceMockGetTutorsIDPreferIndividualParams{studentID},
	}
	mmGetTutorsIDPreferIndividual.expectations = append(mmGetTutorsIDPreferIndividual.expectations, expectation)
	return expectation
}

// Then sets up ServiceInterface.GetTutorsIDPreferIndividual return parameters for the expectation previously defined by the When method
func (e *ServiceMockGetTutorsIDPreferIndividualExpectation) Then(ia1 []int64, b1 bool) *ServiceMock {
	e.results = &ServiceMockGetTutorsIDPreferIndividualResults{ia1, b1}
	return e.mock
}

// GetTutorsIDPreferIndividual implements ServiceInterface
func (mmGetTutorsIDPreferIndividual *ServiceMock) GetTutorsIDPreferIndividual(studentID int64) (ia1 []int64, b1 bool) {
	mm_atomic.AddUint64(&mmGetTutorsIDPreferIndividual.beforeGetTutorsIDPreferIndividualCounter, 1)
	defer mm_atomic.AddUint64(&mmGetTutorsIDPreferIndividual.afterGetTutorsIDPreferIndividualCounter, 1)

	if mmGetTutorsIDPreferIndividual.inspectFuncGetTutorsIDPreferIndividual != nil {
		mmGetTutorsIDPreferIndividual.inspectFuncGetTutorsIDPreferIndividual(studentID)
	}

	mm_params := &ServiceMockGetTutorsIDPreferIndividualParams{studentID}

	// Record call args
	mmGetTutorsIDPreferIndividual.GetTutorsIDPreferIndividualMock.mutex.Lock()
	mmGetTutorsIDPreferIndividual.GetTutorsIDPreferIndividualMock.callArgs = append(mmGetTutorsIDPreferIndividual.GetTutorsIDPreferIndividualMock.callArgs, mm_params)
	mmGetTutorsIDPreferIndividual.GetTutorsIDPreferIndividualMock.mutex.Unlock()

	for _, e := range mmGetTutorsIDPreferIndividual.GetTutorsIDPreferIndividualMock.expectations {
		if minimock.Equal(e.params, mm_params) {
			mm_atomic.AddUint64(&e.Counter, 1)
			return e.results.ia1, e.results.b1
		}
	}

	if mmGetTutorsIDPreferIndividual.GetTutorsIDPreferIndividualMock.defaultExpectation != nil {
		mm_atomic.AddUint64(&mmGetTutorsIDPreferIndividual.GetTutorsIDPreferIndividualMock.defaultExpectation.Counter, 1)
		mm_want := mmGetTutorsIDPreferIndividual.GetTutorsIDPreferIndividualMock.defaultExpectation.params
		mm_got := ServiceMockGetTutorsIDPreferIndividualParams{studentID}
		if mm_want != nil && !minimock.Equal(*mm_want, mm_got) {
			mmGetTutorsIDPreferIndividual.t.Errorf("ServiceMock.GetTutorsIDPreferIndividual got unexpected parameters, want: %#v, got: %#v%s\n", *mm_want, mm_got, minimock.Diff(*mm_want, mm_got))
		}

		mm_results := mmGetTutorsIDPreferIndividual.GetTutorsIDPreferIndividualMock.defaultExpectation.results
		if mm_results == nil {
			mmGetTutorsIDPreferIndividual.t.Fatal("No results are set for the ServiceMock.GetTutorsIDPreferIndividual")
		}
		return (*mm_results).ia1, (*mm_results).b1
	}
	if mmGetTutorsIDPreferIndividual.funcGetTutorsIDPreferIndividual != nil {
		return mmGetTutorsIDPreferIndividual.funcGetTutorsIDPreferIndividual(studentID)
	}
	mmGetTutorsIDPreferIndividual.t.Fatalf("Unexpected call to ServiceMock.GetTutorsIDPreferIndividual. %v", studentID)
	return
}

// GetTutorsIDPreferIndividualAfterCounter returns a count of finished ServiceMock.GetTutorsIDPreferIndividual invocations
func (mmGetTutorsIDPreferIndividual *ServiceMock) GetTutorsIDPreferIndividualAfterCounter() uint64 {
	return mm_atomic.LoadUint64(&mmGetTutorsIDPreferIndividual.afterGetTutorsIDPreferIndividualCounter)
}

// GetTutorsIDPreferIndividualBeforeCounter returns a count of ServiceMock.GetTutorsIDPreferIndividual invocations
func (mmGetTutorsIDPreferIndividual *ServiceMock) GetTutorsIDPreferIndividualBeforeCounter() uint64 {
	return mm_atomic.LoadUint64(&mmGetTutorsIDPreferIndividual.beforeGetTutorsIDPreferIndividualCounter)
}

// Calls returns a list of arguments used in each call to ServiceMock.GetTutorsIDPreferIndividual.
// The list is in the same order as the calls were made (i.e. recent calls have a higher index)
func (mmGetTutorsIDPreferIndividual *mServiceMockGetTutorsIDPreferIndividual) Calls() []*ServiceMockGetTutorsIDPreferIndividualParams {
	mmGetTutorsIDPreferIndividual.mutex.RLock()

	argCopy := make([]*ServiceMockGetTutorsIDPreferIndividualParams, len(mmGetTutorsIDPreferIndividual.callArgs))
	copy(argCopy, mmGetTutorsIDPreferIndividual.callArgs)

	mmGetTutorsIDPreferIndividual.mutex.RUnlock()

	return argCopy
}

// MinimockGetTutorsIDPreferIndividualDone returns true if the count of the GetTutorsIDPreferIndividual invocations corresponds
// the number of defined expectations
func (m *ServiceMock) MinimockGetTutorsIDPreferIndividualDone() bool {
	for _, e := range m.GetTutorsIDPreferIndividualMock.expectations {
		if mm_atomic.LoadUint64(&e.Counter) < 1 {
			return false
		}
	}

	// if default expectation was set then invocations count should be greater than zero
	if m.GetTutorsIDPreferIndividualMock.defaultExpectation != nil && mm_atomic.LoadUint64(&m.afterGetTutorsIDPreferIndividualCounter) < 1 {
		return false
	}
	// if func was set then invocations count should be greater than zero
	if m.funcGetTutorsIDPreferIndividual != nil && mm_atomic.LoadUint64(&m.afterGetTutorsIDPreferIndividualCounter) < 1 {
		return false
	}
	return true
}

// MinimockGetTutorsIDPreferIndividualInspect logs each unmet expectation
func (m *ServiceMock) MinimockGetTutorsIDPreferIndividualInspect() {
	for _, e := range m.GetTutorsIDPreferIndividualMock.expectations {
		if mm_atomic.LoadUint64(&e.Counter) < 1 {
			m.t.Errorf("Expected call to ServiceMock.GetTutorsIDPreferIndividual with params: %#v", *e.params)
		}
	}

	// if default expectation was set then invocations count should be greater than zero
	if m.GetTutorsIDPreferIndividualMock.defaultExpectation != nil && mm_atomic.LoadUint64(&m.afterGetTutorsIDPreferIndividualCounter) < 1 {
		if m.GetTutorsIDPreferIndividualMock.defaultExpectation.params == nil {
			m.t.Error("Expected call to ServiceMock.GetTutorsIDPreferIndividual")
		} else {
			m.t.Errorf("Expected call to ServiceMock.GetTutorsIDPreferIndividual with params: %#v", *m.GetTutorsIDPreferIndividualMock.defaultExpectation.params)
		}
	}
	// if func was set then invocations count should be greater than zero
	if m.funcGetTutorsIDPreferIndividual != nil && mm_atomic.LoadUint64(&m.afterGetTutorsIDPreferIndividualCounter) < 1 {
		m.t.Error("Expected call to ServiceMock.GetTutorsIDPreferIndividual")
	}
}

// MinimockFinish checks that all mocked methods have been called the expected number of times
func (m *ServiceMock) MinimockFinish() {
	if !m.minimockDone() {
		m.MinimockGetTopSubjectsInspect()

		m.MinimockGetTutorsIDPreferIndividualInspect()
		m.t.FailNow()
	}
}

// MinimockWait waits for all mocked methods to be called the expected number of times
func (m *ServiceMock) MinimockWait(timeout mm_time.Duration) {
	timeoutCh := mm_time.After(timeout)
	for {
		if m.minimockDone() {
			return
		}
		select {
		case <-timeoutCh:
			m.MinimockFinish()
			return
		case <-mm_time.After(10 * mm_time.Millisecond):
		}
	}
}

func (m *ServiceMock) minimockDone() bool {
	done := true
	return done &&
		m.MinimockGetTopSubjectsDone() &&
		m.MinimockGetTutorsIDPreferIndividualDone()
}
